In [1]:
# Importing pandas and numpy, always import all packages in a single cell at the top of the notebook
import pandas as pd
import numpy as np

In [2]:
# Using the format s = pd.Series(data, index=index)
# The data can be a list, array, dictionary, sinlge number, boolean, or string
# Creating a pandas.Series from a NumPy array

pd.Series(np.arange(3), index = [2023,2024,2025])

2023    0
2024    1
2025    2
dtype: int64

In [3]:
# Creating a pandas.Series from a list of strings with default index

pd.Series(['EDS 220', 'EDS 222', 'EDS 223', 'EDS 242'])

0    EDS 220
1    EDS 222
2    EDS 223
3    EDS 242
dtype: object

In [4]:
# Creating a pandas.Series from a dictionary

# Construct dictionary
d = {'key_0':2, 'key_1':'3', 'key_2':5}

#Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [5]:
# Crearing a pandas.Series from a single value

pd.Series(3.0, index = ['A', 'B', 'C'])

A    3.0
B    3.0
C    3.0
dtype: float64

Simple Operations

In [7]:
# Define a series
s = pd.Series([98,73,65], index=['Andrea', 'Beth', 'Carolina'])

# Divide each element in series by 10
print(s /10, '\n')

# Take the exponential of each element in a series
print(np.exp(s), '\n')

# Original series is unchanged
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [8]:
# Producing a new pandas.Series with True/False values for a condition

s>70

Andrea       True
Beth         True
Carolina    False
dtype: bool

Identifying Missing Values

In [9]:
# Series with NAs in it
s = pd.Series([1,2,np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [10]:
# Check if series has NAs
s.hasnans

True

In [11]:
# Checking which elements in the series are NAs
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [21]:
# Check in
# Create a pandas.Series named s with four integer values, two of which are -999. 
# The index of this series should be the letters A through D.

s = pd.Series([1,-999,2,-999], index=['A', 'B', 'C', 'D'])
s

A      1
B   -999
C      2
D   -999
dtype: int64

In [19]:
# Using mask() to replace the -999 values with NA.
?pd.Series.mask

Signature:
pd.Series.mask(
    self,
    cond,
    other=<no_default>,
    *,
    inplace: 'bool_t' = False,
    axis: 'Axis | None' = None,
    level: 'Level | None' = None,
) -> 'Self | None'
Docstring:
Replace values where the condition is True.

Parameters
----------
cond : bool Series/DataFrame, array-like, or callable
    Where `cond` is False, keep the original value. Where
    True, replace with corresponding value from `other`.
    If `cond` is callable, it is computed on the Series/DataFrame and
    should return boolean Series/DataFrame or array. The callable must
    not change input Series/DataFrame (though pandas doesn't check it).
other : scalar, Series/DataFrame, or callable
    Entries where `cond` is True are replaced with
    corresponding value from `other`.
    If other is callable, it is computed on the Series/DataFrame and
    should return scalar or Series/DataFrame. The callable must not
    change input Series/DataFrame (though pandas doesn't check it).
    If not specified, entries will be filled with the corresponding
    NULL value (``np.nan`` for numpy dtypes, ``pd.NA`` for extension
    dtypes).
inplace : bool, default False
    Whether to perform the operation in place on the data.
axis : int, default None
    Alignment axis if needed. For `Series` this parameter is
    unused and defaults to 0.
level : int, default None
    Alignment level if needed.

Returns
-------
Same type as caller or None if ``inplace=True``.

See Also
--------
:func:`DataFrame.where` : Return an object of same shape as
    self.

Notes
-----
The mask method is an application of the if-then idiom. For each
element in the calling DataFrame, if ``cond`` is ``False`` the
element is used; otherwise the corresponding element from the DataFrame
``other`` is used. If the axis of ``other`` does not align with axis of
``cond`` Series/DataFrame, the misaligned index positions will be filled with
True.

The signature for :func:`DataFrame.where` differs from
:func:`numpy.where`. Roughly ``df1.where(m, df2)`` is equivalent to
``np.where(m, df1, df2)``.

For further details and examples see the ``mask`` documentation in
:ref:`indexing <indexing.where_mask>`.

The dtype of the object takes precedence. The fill value is casted to
the object's dtype, if this can be done losslessly.

Examples
--------
>>> s = pd.Series(range(5))
>>> s.where(s > 0)
0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64
>>> s.mask(s > 0)
0    0.0
1    NaN
2    NaN
3    NaN
4    NaN
dtype: float64

>>> s = pd.Series(range(5))
>>> t = pd.Series([True, False])
>>> s.where(t, 99)
0     0
1    99
2    99
3    99
4    99
dtype: int64
>>> s.mask(t, 99)
0    99
1     1
2    99
3    99
4    99
dtype: int64

>>> s.where(s > 1, 10)
0    10
1    10
2    2
3    3
4    4
dtype: int64
>>> s.mask(s > 1, 10)
0     0
1     1
2    10
3    10
4    10
dtype: int64

>>> df = pd.DataFrame(np.arange(10).reshape(-1, 2), columns=['A', 'B'])
>>> df
   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9
>>> m = df % 3 == 0
>>> df.where(m, -df)
   A  B
0  0 -1
1 -2  3
2 -4 -5
3  6 -7
4 -8  9
>>> df.where(m, -df) == np.where(m, df, -df)
      A     B
0  True  True
1  True  True
2  True  True
3  True  True
4  True  True
>>> df.where(m, -df) == df.mask(~m, -df)
      A     B
0  True  True
1  True  True
2  True  True
3  True  True
4  True  True
File:      /opt/miniforge3/envs/eds220/lib/python3.11/site-packages/pandas/core/generic.py
Type:      function

In [23]:
s = s.mask(s == -999)
s

A    1.0
B    NaN
C    2.0
D    NaN
dtype: float64

Data Frames

In [24]:
# Creating a pandas.DataFrame

# Initialize dictionary with columns' data
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1,3.2,3.3])
    }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [25]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [28]:
# Check-in

# Update the column names to C1 and C2 via the columns attribute

df.columns = ['C1','C2']
df

   C1   C2
a   0  3.1
b   1  3.2
c   2  3.3